<a href="https://colab.research.google.com/github/ardianita/data-science-2026/blob/main/Pertemuan_3_Ardianita_Fauziyah_NIM_250401020128.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama  : Ardianita Fauziyah

NIM   : 250401020128

Kelas : IF403

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize

# Memuat Dataset
df = pd.read_csv("https://drive.google.com/uc?id=1LfQWProB0VjWN5q8bKuRIgn-stULfIRo")
df

      id  luas_m2  harga_juta        kota  kamar  tahun_bangun kondisi
0      1    297.0      1084.0       jogja    2.0          2000    baik
1      2    254.0       761.0       Medan    NaN          1995   Bagus
2      3    249.7       895.0       Depok    NaN          1983    baik
3      4     49.7       178.0         YGY    5.0          2013    baik
4      5    133.4       424.0       Medan    5.0          2004  Sedang
..   ...      ...         ...         ...    ...           ...     ...
125  126    330.2      1050.0    Semarang    6.0          1993    Baik
126  127      NaN         NaN    Makassar    5.0          2008    baik
127  128     84.1       202.0    Makassar    2.0          1986    Baik
128  129     88.0       252.0    makassar    NaN          1986   Bagus
129  130    215.4       941.0  yogyakarta    1.0          2013   Cukup

[130 rows x 7 columns]

In [ ]:
# Eksplorasi Dataset

print('Shape awal:')
print(df.shape);

print(f'\nTipe data:');
df.info();

print(f'\nStatistik deskripsi:')
print(df.describe());

print(f'\nMissing value')
print(df.isnull().sum());

Shape awal:
(130, 7)

Tipe data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB

Statistik deskripsi:
               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000

Missing value
id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

In [ ]:
# Hapus duplikasi
df.drop_duplicates(inplace=True);
print(f"Total Data Duplikat : {df.duplicated().sum()}")
print(f"\nShape Akhir")
print(f"Baris: {df.shape[0]}");
print(f"Kolom: {df.shape[1]}");

Total Data Duplikat : 0

Shape Akhir
Baris: 130
Kolom: 7

In [ ]:
# Normalisasi String

# Normalisasi nama kota dengan capital di huruf awal
df['kota']    = df['kota'].str.strip().str.title()

# Normalisasi kondisi menjadi huruf kecil
df['kondisi'] = df['kondisi'].str.strip().str.lower()

print("Dataset setelah normalisasi")
df

Dataset setelah normalisasi

      id  luas_m2  harga_juta        kota  kamar  tahun_bangun kondisi
0      1    297.0      1084.0       Jogja    2.0          2000    baik
1      2    254.0       761.0       Medan    NaN          1995   bagus
2      3    249.7       895.0       Depok    NaN          1983    baik
3      4     49.7       178.0         Ygy    5.0          2013    baik
4      5    133.4       424.0       Medan    5.0          2004  sedang
..   ...      ...         ...         ...    ...           ...     ...
125  126    330.2      1050.0    Semarang    6.0          1993    baik
126  127      NaN         NaN    Makassar    5.0          2008    baik
127  128     84.1       202.0    Makassar    2.0          1986    baik
128  129     88.0       252.0    Makassar    NaN          1986   bagus
129  130    215.4       941.0  Yogyakarta    1.0          2013   cukup

[130 rows x 7 columns]

In [ ]:
# Imputasi missing values

# Imputasi median value luas
df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())

# Imputasi median value harga_jual
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())

# Imputasi modus value kamar
df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

# Dataset setelah imputasi
print('Dataset Setelah Imputasi')
df

Dataset Setelah Imputasi

      id  luas_m2  harga_juta        kota  kamar  tahun_bangun kondisi
0      1    297.0      1084.0       Jogja    2.0          2000    baik
1      2    254.0       761.0       Medan    1.0          1995   bagus
2      3    249.7       895.0       Depok    1.0          1983    baik
3      4     49.7       178.0         Ygy    5.0          2013    baik
4      5    133.4       424.0       Medan    5.0          2004  sedang
..   ...      ...         ...         ...    ...           ...     ...
125  126    330.2      1050.0    Semarang    6.0          1993    baik
126  127    193.8       655.0    Makassar    5.0          2008    baik
127  128     84.1       202.0    Makassar    2.0          1986    baik
128  129     88.0       252.0    Makassar    1.0          1986   bagus
129  130    215.4       941.0  Yogyakarta    1.0          2013   cukup

[130 rows x 7 columns]

In [ ]:
# Menangani outlier dengan IQR
for col in ['harga_juta', 'luas_m2']:
    Q1, Q3 = df[col].quantile([0.25, 0.75])

    # IQR
    IQR = Q3 - Q1

    # Batas bawah & atas
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    # Outlier
    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"\nKolom: {col}")
    print(f"Batas bawah: {lower:.0f}")
    print(f"Batas atas : {upper:.0f}")
    print(f"Jumlah outlier: {len(outliers)} baris")

Kolom: harga_juta
Batas bawah: -423
Batas atas : 1719
Jumlah outlier: 0 baris

Kolom: luas_m2
Batas bawah: -145
Batas atas : 513
Jumlah outlier: 0 baris

In [ ]:
# Validasi Akhir

print(f'Missing value')
print(df.isnull().sum())

duplikat = df.duplicated().sum()
print(f'\nTotal Duplikasi Data : {duplikat}')

Missing value
id              0
luas_m2         0
harga_juta      0
kota            0
kamar           0
tahun_bangun    0
kondisi         0
dtype: int64

Total Duplikasi Data : 0

In [ ]:
df.to_csv('housing_clean.csv', index=False)
print('Dataset bersih tersimpan!')

Dataset bersih tersimpan!

In [ ]:
import requests
import pandas as pd
import json

URL = "https://jsonplaceholder.typicode.com/users"

# Akses API
response = requests.get(URL)
if response.status_code == 200:
  print('Berhasil Akses API')

  # Simpan json dalam data frame
  data = response.json()
  df = pd.DataFrame(data)
  print(df)
else:
  print(f'Gagal Akses API : {response.status_code}')

Berhasil Akses API
   id                      name          username                      email  \
0   1             Leanne Graham              Bret          Sincere@april.biz
1   2              Ervin Howell         Antonette          Shanna@melissa.tv
2   3          Clementine Bauch          Samantha         Nathan@yesenia.net
3   4          Patricia Lebsack          Karianne  Julianne.OConner@kory.org
4   5          Chelsey Dietrich            Kamren   Lucio_Hettinger@annie.ca
5   6      Mrs. Dennis Schulist  Leopoldo_Corkery    Karley_Dach@jasper.info
6   7           Kurtis Weissnat      Elwyn.Skiles     Telly.Hoeger@billy.biz
7   8  Nicholas Runolfsdottir V     Maxime_Nienow       Sherwood@rosamond.me
8   9           Glenna Reichert          Delphine    Chaim_McDermott@dana.io
9  10        Clementina DuBuque    Moriah.Stanton     Rey.Padberg@karina.biz

                                             address                  phone  \
0  {'street': 'Kulas Light', 'suite': 'Apt. 556',...  1-770-736-8031 x56442
1  {'street': 'Victor Plains', 'suite': 'Suite 87...    010-692-6593 x09125
2  {'street': 'Douglas Extension', 'suite': 'Suit...         1-463-123-4447
3  {'street': 'Hoeger Mall', 'suite': 'Apt. 692',...      493-170-9623 x156
4  {'street': 'Skiles Walks', 'suite': 'Suite 351...          (254)954-1289
5  {'street': 'Norberto Crossing', 'suite': 'Apt....   1-477-935-8478 x6430
6  {'street': 'Rex Trail', 'suite': 'Suite 280', ...           210.067.6132
7  {'street': 'Ellsworth Summit', 'suite': 'Suite...      586.493.6943 x140
8  {'street': 'Dayna Park', 'suite': 'Suite 449',...   (775)976-6794 x41206
9  {'street': 'Kattie Turnpike', 'suite': 'Suite ...           024-648-3804

         website                                            company
0  hildegard.org  {'name': 'Romaguera-Crona', 'catchPhrase': 'Mu...
1  anastasia.net  {'name': 'Deckow-Crist', 'catchPhrase': 'Proac...
2    ramiro.info  {'name': 'Romaguera-Jacobson', 'catchPhrase': ...
3       kale.biz  {'name': 'Robel-Corkery', 'catchPhrase': 'Mult...
4   demarco.info  {'name': 'Keebler LLC', 'catchPhrase': 'User-c...
5        ola.org  {'name': 'Considine-Lockman', 'catchPhrase': '...
6       elvis.io  {'name': 'Johns Group', 'catchPhrase': 'Config...
7   jacynthe.com  {'name': 'Abernathy Group', 'catchPhrase': 'Im...
8     conrad.com  {'name': 'Yost and Sons', 'catchPhrase': 'Swit...
9    ambrose.net  {'name': 'Hoeger LLC', 'catchPhrase': 'Central...

**Kesimpulan** : Melalui pertemuan ini, saya mempelajari cara mengidentifikasi outlier, duplikasi data dan missing value dalam sebuah dataset. Selain itu, dibahas pula strategi penanganan untuk outlier, duplikasi data, dan missing value tersebut